name: Docker Image CI
on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * 1' # 每周一运行一次

env:
  IMAGE_NAME: ai-excalidraw
  UPSTREAM_REPO: https://github.com/co-pine/ai-excalidraw.git

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository # 签出代码
        uses: actions/checkout@v4

      - name: Convert owner to lowercase # 转换仓库所有者
        id: set-owner
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "Registry owner set to: $OWNER"
      
      - name: Get current date # 获取当前日期
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry # 登录到 GitHub 容器注册表
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone upstream repository # 克隆上游仓库
        run: |
          git clone ${{ env.UPSTREAM_REPO }}

      - name: Set up Docker Buildx # 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image # 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}